export const mobileLayout = {
  shell: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    paddingBottom: 'calc(64px + env(safe-area-inset-bottom, 0px))',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'calc(12px + env(safe-area-inset-top, 0px)) 16px 12px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg2)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  topBrand: {
    fontFamily: 'var(--font-display)',
    fontSize: 20,
    letterSpacing: 2,
  },
  topMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  topName: {
    fontSize: 12,
    color: 'var(--text2)',
    maxWidth: 100,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  main: {
    flex: 1,
    padding: '20px 16px',
    width: '100%',
    animation: 'fadeUp 0.35s ease',
  },
  tabBar: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    background: 'var(--bg2)',
    borderTop: '1px solid var(--border)',
    paddingBottom: 'env(safe-area-inset-bottom, 0px)',
    zIndex: 20,
  },
  tab: {
    flex: 1,
    padding: '10px 4px 12px',
    background: 'transparent',
    color: 'var(--text3)',
    fontSize: 11,
    fontWeight: 500,
    textAlign: 'center',
  },
  tabActive: {
    color: 'var(--teal)',
  },
};

export const listCard = {
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  item: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    padding: '14px 16px',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 8,
  },
  title: {
    fontSize: 15,
    fontWeight: 600,
    marginBottom: 4,
  },
  sub: {
    fontSize: 12,
    color: 'var(--text3)',
    fontFamily: 'var(--font-mono)',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTop: '1px solid var(--border)',
  },
};

export const layout = {
  shell: {
    display: 'flex',
    minHeight: '100vh',
  },
  sidebar: {
    width: 240,
    flexShrink: 0,
    background: 'linear-gradient(180deg, var(--bg2) 0%, var(--surface) 100%)',
    borderRight: '1px solid var(--border)',
    display: 'flex',
    flexDirection: 'column',
    padding: '28px 16px',
    position: 'sticky',
    top: 0,
    height: '100vh',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '0 8px 28px',
    borderBottom: '1px solid var(--border)',
    marginBottom: 24,
  },
  brandIcon: {
    color: 'var(--teal)',
    fontSize: 18,
    textShadow: '0 0 12px var(--teal-glow)',
  },
  brandTitle: {
    fontFamily: 'var(--font-display)',
    fontSize: 22,
    letterSpacing: 2,
    lineHeight: 1,
    display: 'block',
  },
  brandSub: {
    fontFamily: 'var(--font-mono)',
    fontSize: 9,
    color: 'var(--text3)',
    letterSpacing: 2,
    display: 'block',
    marginTop: 4,
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
  },
  sidebarFoot: {
    borderTop: '1px solid var(--border)',
    paddingTop: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  adminName: {
    fontSize: 13,
    color: 'var(--text2)',
    padding: '0 8px',
  },
  main: {
    flex: 1,
    padding: '32px 40px',
    maxWidth: 1200,
    width: '100%',
    animation: 'fadeUp 0.35s ease',
  },
};

export const nav = {
  item: {
    textAlign: 'left',
    padding: '12px 14px',
    borderRadius: 10,
    background: 'transparent',
    color: 'var(--text2)',
    fontSize: 14,
    fontWeight: 500,
    width: '100%',
  },
  itemActive: {
    background: 'var(--teal-glow)',
    color: 'var(--teal)',
    border: '1px solid rgba(0,201,167,0.25)',
  },
  logoutBtn: {
    background: 'transparent',
    border: '1px solid var(--border2)',
    borderRadius: 8,
    padding: '10px 14px',
    color: 'var(--text2)',
    fontSize: 13,
    width: '100%',
  },
  logoutBtnCompact: {
    background: 'transparent',
    border: '1px solid var(--border2)',
    borderRadius: 8,
    padding: '6px 10px',
    color: 'var(--text2)',
    fontSize: 11,
    whiteSpace: 'nowrap',
  },
};

export const page = {
  header: { marginBottom: 28 },
  eyebrow: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--teal)',
    letterSpacing: 3,
    marginBottom: 8,
  },
  title: { fontSize: 28, fontWeight: 700, marginBottom: 6 },
  sub: { fontSize: 13, color: 'var(--text2)', fontFamily: 'var(--font-mono)' },
};

export const card = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
    marginBottom: 28,
  },
  stat: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    padding: '22px 24px',
  },
  statLabel: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text3)',
    letterSpacing: 1,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 32,
    fontWeight: 700,
    fontFamily: 'var(--font-display)',
    letterSpacing: 1,
  },
};

export const table = {
  wrap: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    overflow: 'hidden',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    textAlign: 'left',
    padding: '14px 16px',
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text3)',
    letterSpacing: 1,
    background: 'var(--surface2)',
    borderBottom: '1px solid var(--border)',
  },
  td: {
    padding: '14px 16px',
    fontSize: 13,
    borderBottom: '1px solid var(--border)',
    color: 'var(--text)',
    verticalAlign: 'middle',
  },
  empty: {
    padding: 48,
    textAlign: 'center',
    color: 'var(--text3)',
    fontFamily: 'var(--font-mono)',
    fontSize: 13,
  },
};

export const badge = {
  admin: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: 20,
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    background: 'var(--gold-glow)',
    color: 'var(--gold)',
    border: '1px solid rgba(245,166,35,0.3)',
  },
  user: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: 20,
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    background: 'var(--teal-glow)',
    color: 'var(--teal)',
    border: '1px solid rgba(0,201,167,0.25)',
  },
  pending: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: 20,
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text3)',
    border: '1px solid var(--border2)',
    background: 'transparent',
  },
};

export const btn = {
  small: {
    padding: '6px 12px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    background: 'var(--surface2)',
    border: '1px solid var(--border2)',
    color: 'var(--text2)',
  },
  danger: {
    padding: '6px 12px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    background: 'var(--red-glow)',
    border: '1px solid rgba(255,77,109,0.35)',
    color: 'var(--red)',
  },
  select: {
    background: 'var(--surface2)',
    border: '1px solid var(--border2)',
    borderRadius: 8,
    padding: '6px 10px',
    color: 'var(--text)',
    fontSize: 12,
  },
};

export const login = {
  page: { display: 'flex', minHeight: '100dvh' },
  pageCompact: { flexDirection: 'column' },
  brand: {
    width: '42%',
    background: 'linear-gradient(145deg, #0D1117 0%, var(--surface) 50%, #0A1520 100%)',
    borderRight: '1px solid var(--border)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '48px 52px',
    position: 'relative',
    overflow: 'hidden',
  },
  brandCompact: {
    width: '100%',
    borderRight: 'none',
    borderBottom: '1px solid var(--border)',
    padding: 'calc(28px + env(safe-area-inset-top, 0px)) 24px 24px',
  },
  heroTitle: { fontSize: 42, fontWeight: 700, lineHeight: 1.2, marginBottom: 12 },
  heroTitleCompact: { fontSize: 32, marginBottom: 8 },
  heroSub: { fontSize: 14, color: 'var(--text2)', marginBottom: 32, maxWidth: 280 },
  heroSubCompact: { fontSize: 13, marginBottom: 0, maxWidth: 'none' },
  featureList: {
    listStyle: 'none',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 14,
    color: 'var(--text2)',
  },
  featureDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: 'var(--teal)',
    boxShadow: '0 0 8px var(--teal)',
    flexShrink: 0,
  },
  glow: {
    position: 'absolute',
    top: -80,
    right: -80,
    width: 320,
    height: 320,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(0,201,167,0.12) 0%, transparent 68%)',
    pointerEvents: 'none',
  },
  formSide: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px',
  },
  formSideCompact: {
    padding: '28px 20px calc(28px + env(safe-area-inset-bottom, 0px))',
    alignItems: 'stretch',
  },
  formWrap: { width: '100%', maxWidth: 400 },
  eyebrow: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--teal)',
    letterSpacing: 3,
    marginBottom: 12,
  },
  title: { fontSize: 30, fontWeight: 700, marginBottom: 8 },
  sub: { fontSize: 13, color: 'var(--text2)', fontFamily: 'var(--font-mono)', marginBottom: 32 },
  field: { display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 16 },
  label: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text2)', letterSpacing: 1 },
  input: {
    background: 'var(--surface)',
    border: '1px solid var(--border2)',
    borderRadius: 10,
    padding: '12px 16px',
    color: 'var(--text)',
    fontSize: 14,
    width: '100%',
  },
  error: {
    background: 'rgba(255,80,80,0.08)',
    border: '1px solid rgba(255,80,80,0.3)',
    borderRadius: 8,
    padding: '10px 14px',
    color: '#ff6b6b',
    fontSize: 13,
    fontFamily: 'var(--font-mono)',
    marginBottom: 16,
  },
  submit: {
    width: '100%',
    background: 'linear-gradient(135deg, var(--teal), #00A88A)',
    color: '#000',
    borderRadius: 10,
    padding: 14,
    fontSize: 14,
    fontWeight: 700,
    marginTop: 8,
  },
};
