export const detail = {
  wrap: { animation: 'fadeUp 0.3s ease' },
  wrapCompact: { paddingBottom: 8 },
  topBar: { marginBottom: 20 },
  backBtn: {
    background: 'none',
    border: '1px solid var(--border2)',
    borderRadius: 8,
    padding: '8px 14px',
    color: 'var(--text2)',
    fontSize: 13,
    fontFamily: 'var(--font-mono)',
  },
  loading: { color: 'var(--text3)', fontFamily: 'var(--font-mono)', fontSize: 13 },
  header: { marginBottom: 28 },
  eyebrow: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--teal)',
    letterSpacing: 3,
    marginBottom: 8,
  },
  title: { fontSize: 26, fontWeight: 700, marginBottom: 10 },
  metaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    fontSize: 13,
    color: 'var(--text2)',
    fontFamily: 'var(--font-mono)',
    marginBottom: 12,
  },
  downloadLink: {
    display: 'inline-block',
    fontSize: 13,
    color: 'var(--teal)',
    textDecoration: 'none',
    fontFamily: 'var(--font-mono)',
  },
  summaryCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    padding: '24px 28px',
    marginBottom: 28,
  },
  sectionTitle: { fontSize: 16, fontWeight: 700, marginBottom: 18 },
  scoreRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  scoreLabel: { fontSize: 12, fontFamily: 'var(--font-mono)', color: 'var(--text2)', minWidth: 72 },
  scoreNum: { fontSize: 14, fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--teal)' },
  barWrap: {
    flex: 1,
    minWidth: 120,
    height: 8,
    background: 'var(--surface2)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: 4, transition: 'width 0.4s ease' },
  fbSection: { marginTop: 16 },
  fbLabel: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text3)',
    letterSpacing: 1,
    marginBottom: 8,
  },
  fbText: {
    fontSize: 14,
    color: 'var(--text)',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
  },
  pendingCard: {
    padding: 24,
    textAlign: 'center',
    color: 'var(--text3)',
    background: 'var(--surface)',
    border: '1px dashed var(--border2)',
    borderRadius: 12,
    fontFamily: 'var(--font-mono)',
    fontSize: 13,
  },
  slideSection: { marginTop: 8 },
  slideList: { display: 'flex', flexDirection: 'column', gap: 14 },
  slideCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  slideHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    background: 'var(--surface2)',
    borderBottom: '1px solid var(--border)',
  },
  slideIndex: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--teal)', letterSpacing: 2 },
  scoreBadge: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    padding: '3px 10px',
    borderRadius: 20,
    border: '1px solid',
  },
  slideBody: { padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 14 },
  statRow: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '5px 10px',
    background: 'var(--surface2)',
    borderRadius: 8,
    border: '1px solid var(--border)',
  },
  chipLabel: { fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text3)' },
  chipVal: { fontSize: 12, fontWeight: 600, color: 'var(--text)' },
  transcriptBox: {
    background: 'var(--bg2)',
    borderRadius: 8,
    padding: '12px 14px',
    border: '1px solid var(--border)',
  },
  transcriptLabel: {
    fontSize: 10,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text3)',
    marginBottom: 6,
    letterSpacing: 1,
  },
  transcriptText: { fontSize: 13, color: 'var(--text2)', lineHeight: 1.6 },
  feedbackBlock: { marginTop: 4 },
  feedbackBlockLabel: {
    fontSize: 10,
    fontFamily: 'var(--font-mono)',
    color: 'var(--gold)',
    marginBottom: 6,
    letterSpacing: 1,
  },
  feedbackBlockText: { fontSize: 13, color: 'var(--text)', lineHeight: 1.6 },
};
